window.GOLF_COURSES = [
  {
    "id": "royal-melbourne-golf-club",
    "name": "Royal Melbourne Golf Club",
    "town": "Black Rock",
    "region": "Melbourne Sandbelt",
    "state": "VIC",
    "coordinates": [145.0287, -37.9697],
    "holes": "36",
    "access": "Private club",
    "priceLevel": 5,
    "homepageUrl": "https://www.royalmelbourne.com.au/",
    "bookingUrl": "",
    "imageUrl": "https://icons.duckduckgo.com/ip3/royalmelbourne.com.au.ico",
    "fallbackImageUrl": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/59317/40256",
    "imageAlt": "Royal Melbourne Golf Club logo",
    "mediaKind": "logo",
    "summary": "36 hole private club in Black Rock, Victoria.",
    "webSearchUrl": "https://www.google.com/search?q=Royal%20Melbourne%20Golf%20Club%20Black%20Rock%20VIC%20golf%20club%20website"
  },
  {
    "id": "barnbougle-dunes",
    "name": "Barnbougle Dunes",
    "town": "Bridport",
    "region": "Tasmania",
    "state": "TAS",
    "coordinates": [147.4385, -40.9979],
    "holes": "18",
    "access": "Public access",
    "priceLevel": 5,
    "homepageUrl": "https://barnbougle.com.au/",
    "bookingUrl": "https://barnbougle.com.au/book/",
    "imageUrl": "https://icons.duckduckgo.com/ip3/barnbougle.com.au.ico",
    "fallbackImageUrl": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/59538/40526",
    "imageAlt": "Barnbougle Dunes logo",
    "mediaKind": "logo",
    "summary": "18 hole public access links course near Bridport, Tasmania.",
    "webSearchUrl": "https://www.google.com/search?q=Barnbougle%20Dunes%20Bridport%20TAS%20golf%20club%20website"
  },
  {
    "id": "brookwater-golf-country-club",
    "name": "Brookwater Golf & Country Club",
    "town": "Brookwater",
    "region": "Ipswich",
    "state": "QLD",
    "coordinates": [152.8935, -27.658],
    "holes": "18",
    "access": "Golf club",
    "priceLevel": 4,
    "homepageUrl": "https://brookwater.com.au/",
    "bookingUrl": "",
    "imageUrl": "https://icons.duckduckgo.com/ip3/brookwater.com.au.ico",
    "fallbackImageUrl": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/59498/36942",
    "imageAlt": "Brookwater Golf & Country Club logo",
    "mediaKind": "logo",
    "summary": "18 hole golf club in Brookwater, Queensland.",
    "webSearchUrl": "https://www.google.com/search?q=Brookwater%20Golf%20Country%20Club%20QLD%20golf%20club%20website"
  },
  {
    "id": "joondalup-resort",
    "name": "Joondalup Resort",
    "town": "Connolly",
    "region": "Perth",
    "state": "WA",
    "coordinates": [115.7467, -31.748],
    "holes": "27",
    "access": "Resort course",
    "priceLevel": 4,
    "homepageUrl": "https://www.joondalupresort.com.au/",
    "bookingUrl": "",
    "imageUrl": "https://icons.duckduckgo.com/ip3/joondalupresort.com.au.ico",
    "fallbackImageUrl": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/53848/38195",
    "imageAlt": "Joondalup Resort logo",
    "mediaKind": "logo",
    "summary": "27 hole resort course in Connolly, Western Australia.",
    "webSearchUrl": "https://www.google.com/search?q=Joondalup%20Resort%20golf%20course%20WA"
  },
  {
    "id": "kooyonga-golf-club",
    "name": "Kooyonga Golf Club",
    "town": "Lockleys",
    "region": "Adelaide",
    "state": "SA",
    "coordinates": [138.5287, -34.921],
    "holes": "18",
    "access": "Private club",
    "priceLevel": 5,
    "homepageUrl": "https://www.kooyongagolf.com.au/",
    "bookingUrl": "",
    "imageUrl": "https://icons.duckduckgo.com/ip3/kooyongagolf.com.au.ico",
    "fallbackImageUrl": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/57994/39383",
    "imageAlt": "Kooyonga Golf Club logo",
    "mediaKind": "logo",
    "summary": "18 hole private club in Lockleys, South Australia.",
    "webSearchUrl": "https://www.google.com/search?q=Kooyonga%20Golf%20Club%20Adelaide%20SA%20golf%20club%20website"
  }
];
